version: '3.8'
services:
  frontend:
    build:
      context: ./bachelor Project/frontend  # 正确的前端项目路径
      dockerfile: Dockerfile  # 指定 Dockerfile 的名称和
    depends_on:
      - backend  # 前端依赖后端服务启动
    networks:
      indilearn-network:
        ipv4_address: 172.21.0.2
    restart: always

  backend:
    build:
      context: ./  # 设置 Dockerfile 的上下文目录为项目根目录
      dockerfile: Dockerfile  # 指定后端 Dockerfile 的名称和位置
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - FLASK_RUN_HOST=0.0.0.0
    volumes:
      - .:/app  # 映射整个项目目录
    depends_on:
      - db  # 后端依赖数据库服务启动
    networks:
      indilearn-network:
        ipv4_address: 172.21.0.3
    restart: always

  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=472372239 # 你应该使用环境变量或secrets来避免在配置文件中硬编码密码
      - POSTGRES_DB=users
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      indilearn-network:
        ipv4_address: 172.21.0.4
    restart: always

volumes:
  postgres_data:


networks:
  indilearn-network:
    ipam:
      config:
        - subnet: 172.21.0.0/16