"""Generate initial migration

Revision ID: fbf15fb6804c
Revises: 
Create Date: 2023-11-20 20:29:02.774760

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fbf15fb6804c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aufgaben',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('aufgabenstellung', sa.String(), nullable=True),
    sa.Column('musterloesung', sa.String(), nullable=True),
    sa.Column('kategorie', sa.String(), nullable=True),
    sa.Column('schwerigkeit', sa.Float(precision=1), nullable=True),
    sa.Column('discrimination', sa.Float(precision=1), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('email_addresses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('address')
    )
    op.create_table('emails',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recipient_email', sa.String(), nullable=True),
    sa.Column('subject', sa.String(), nullable=True),
    sa.Column('message', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_sent', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('leistung',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('aufgabestellung', sa.String(), nullable=True),
    sa.Column('score', sa.Boolean(), nullable=True),
    sa.Column('kategorie', sa.String(), nullable=True),
    sa.Column('schwerigkeit', sa.Float(precision=1), nullable=True),
    sa.Column('typ', sa.String(), nullable=True),
    sa.Column('zeitpunkt', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('level',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('faehigkeit', sa.Float(precision=1), nullable=True),
    sa.Column('kategorie', sa.String(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mysubject',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fachname', sa.String(), nullable=True),
    sa.Column('username', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('studentUsers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('userTyp', sa.String(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('user_ranks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['username'], ['studentUsers.username'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_ranks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_ranks_username'), ['username'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_ranks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_ranks_username'))

    op.drop_table('user_ranks')
    op.drop_table('studentUsers')
    op.drop_table('mysubject')
    op.drop_table('level')
    op.drop_table('leistung')
    op.drop_table('emails')
    op.drop_table('email_addresses')
    op.drop_table('aufgaben')
    # ### end Alembic commands ###
